# Generated by Django 5.1.2 on 2024-11-18 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1200)),
        ),
    ]
