# Generated by Django 5.1.2 on 2024-11-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_visit_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='duration',
        ),
    ]
