# Generated by Django 5.1.2 on 2024-11-18 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1200)),
        ),
    ]
