from .doctor import DoctorListSerializer, DoctorRetrieveSerializer, DoctorUpdateSerializer, DoctorCreateSerializer
from .patient import PatientListSerializer, PatientDetailedSerializer, PatientCreateOrUpdateSerializer
from .service import ServiceUpdateSerializer, ServiceCreateSerializer, ServiceRetrieveSerializer, ServiceListSerializer
